name: RMenu
options:
  bundleIdPrefix: com.yeshan333
  deploymentTarget:
    macOS: "14.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  RMenu:
    type: application
    platform: macOS
    sources:
      - path: RMenu
        excludes:
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yeshan333.RMenu
        INFOPLIST_FILE: RMenu/Info.plist
        CODE_SIGN_ENTITLEMENTS: RMenu/RMenu.entitlements
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    dependencies:
      - target: RMenuExtension
        embed: true
        codeSign: true
        buildPhase:
          copyFiles:
            destination: plugins

  RMenuExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: RMenuExtension
        excludes:
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yeshan333.RMenu.FinderSyncExtension
        INFOPLIST_FILE: RMenuExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: RMenuExtension/RMenuExtension.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../../../../../Frameworks"
    frameworks:
      - sdk: FinderSync.framework
